# This workflow will update documentation using Sphinx and push changes to the Github page.

name: Update docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install sphinx sphinx_rtd_theme sphinx-automodapi
    - name: Build documentation
      run: |
        cd sphinx
        make html
        cd ../
        cp -a ./sphinx/build/html/. ./docs/
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "Update package documentation with Sphinx"
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
